name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    environment: prod_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Dependencies and Build
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade flit
          make dist

      - name: Get Changelog
        run: |
          awk -v ver=${GITHUB_REF#refs/*/} '
            /^## \[v/ { if (p){exit}; if ($2 ~ ver){p=1; next} } p && NF
          ' CHANGELOG.md > CURRENT_CHANGELOG.txt
          cat CURRENT_CHANGELOG.txt

      - name: Create Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        with:
          body_path: CURRENT_CHANGELOG.txt
          files: dist/*.whl
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish on PyPI
        if: ${{ steps.gh_release.outputs.url }}
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: make release
