name: Publish Package

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    environment: prod_release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade flit

      - name: Build and Publish
        if: ${{ steps.gh_release.outputs.url }}
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          echo ${{ steps.gh_release.outputs }}
          echo ${{ steps.gh_release.outputs.id }}
          echo ${{ steps.gh_release.outputs.url }}
          echo ${{ steps.gh_release.outputs.upload_url }}
